barra_recipe_recipes_admin:
  path:     /recipes/{pageIndex}
  defaults: { _controller: BarraAdminBundle:Recipe:recipesAdmin, pageIndex: 1 }
  requirements:
    pageIndex: \d+

barra_recipe_recipe_admin:
  path:     /recipe/{name}
  defaults: { _controller: BarraAdminBundle:Recipe:recipeAdmin }

barra_recipe_manufacturers:
  path:     /manufacturers/{pageIndex}
  defaults: { _controller: BarraAdminBundle:Manufacturer:index, pageIndex: 1 }
  requirements:
    pageIndex: \d+

barra_recipe_measurements:
  path:     /measurements/{pageIndex}
  defaults: { _controller: BarraAdminBundle:Measurement:index, pageIndex: 1 }
  requirements:
    pageIndex: \d+

barra_recipe_products:
  path:     /products/{pageIndex}
  defaults: { _controller: BarraAdminBundle:Product:index, pageIndex: 1 }
  requirements:
    pageIndex: \d+