language: php

branches:
    only: [master]

cache:
    directories: [~/.composer/cache/files]

php: [5.6, 7.0]

services: mysql

before_install:
    - mysql -e 'create database vpit_test;'
    - composer self-update
install:
    - composer install --no-interaction --prefer-dist

before_script:
    - php -v
    - bin/console doctrine:schema:create --env=test
script:
    - composer validate
    - bin/phpunit
