language: php
php:
    - '5.6'
    - hhvm

services: mysql

before_script:
    - mysql -e 'create database vpit_test;'
    - bin/build prod
    - bin/console doctrine:schema:create --env=test

script: bin/phpunit --configuration var/
