language: php

branches:
    only: [master]

cache:
    directories: [~/.composer/cache/files]

php: [7.0, 7.1]

before_install:
    - composer self-update
install:
    - composer install --no-interaction --prefer-dist

before_script:
    - php -v
script:
    - composer validate
    - bin/phpunit
