var webpackConfig = require('./app/Resources/webpack/webpack.test').webpackConfig({env: 'test'});
var NormalModuleReplacementPlugin = require('webpack').NormalModuleReplacementPlugin;

/*
 * main.ts imports modules, generated by symfony.
 * To decouple js tests from symfony, the imported modules are replaced with empty ones.
 */
var moduleReplacementPlugin = new NormalModuleReplacementPlugin(/web\/(js|bundles)\//, 'tests/karma/empty');
webpackConfig.plugins.push(moduleReplacementPlugin);

module.exports = (config) => {
    config.set({
        browserNoActivityTimeout: 60000,
        browsers: [
            'ChromeHeadless',
        ],
        frameworks: [
            'jasmine',
        ],
        plugins: [
            'karma-chrome-launcher',
            'karma-jasmine',
            'karma-mocha-reporter',
            'karma-sourcemap-loader',
            'karma-webpack',
        ],
        reporters: [
            'progress',
            'mocha',
        ],

        /*
         * karmaWebpackConfig
         */
        beforeMiddleware: [
            'webpackBlocker',
        ],
        files: [
            'app/Resources/public/js/tests/karma/test-main.js',
        ],
        preprocessors: {
            'app/Resources/public/js/tests/karma/test-main.js': ['webpack', 'sourcemap'],
        },
        webpack: webpackConfig,
        webpackMiddleware: {
            stats: 'errors-only',
        },
    });
};
