imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@BarraBackBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~                                      # handler_id set to null will use default session handler from php.ini
    fragments:       ~
    http_method_override: true
    translator: { fallbacks: en }                           # language(-file) if requested translation file is not found
    default_locale:  de                                     # for links, when no favorite given default %locale%


sensio_framework_extra:
    view: { annotations: false }                            # FOSRestBundle takes over the controller annotations handling for views


twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
 #   form:
  #      resources:
   #         - 'BarraBackBundle:Form:tableRow.html.twig'     # for autoinclude


doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

assetic:
  debug:          "%kernel.debug%"
  use_controller: false
  bundles:        [ BarraBackBundle, BarraFrontBundle, FOSUserBundle, TwigBundle ] # User & Twig for overwritten templates
  filters:
      cssrewrite: ~


swiftmailer:
    transport:  "%mailer_transport%"
    encryption: "%mailer_encryption%"
    auth_mode:  "%mailer_auth_mode%"
    port:       "%mailer_port%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:     { type: memory }                             # sends after request is completely processed (w/o exception or error)


fos_rest:
    param_fetcher_listener: true                            # reading parameters from the request
    format_listener: true                                   # determining the correct response format
    body_listener:                                          # decoding the request content
        decoders:
          json: fos_rest.decoder.jsontoform                 # for checkboxes with boolean values
          xml: fos_rest.decoder.xml
          #array_normalizer: fos_rest.normalizer.camel_keys # transform underscored array keys to camel cased ones [be aware of form_name]
    view:
        view_response_listener: 'force'                     # formatting the response (with twig or serializer [xml/json])
        formats:                                            # serializer for rendering
            xml: true
            json : true
        templating_formats:                                 # template for rendering via templating service
            html: false                                     # false to don't have to support separate twig templates
        force_redirects:
            html: true                                      # default
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json                                # if none is set via URL


fos_user:
    db_driver:      orm
    firewall_name:  admino
    user_class:     Barra\FrontBundle\Entity\User


jms_serializer:                                             # JMS exlusion for 3th party entites needs to be done via config file
    metadata:
        directories:
            FOSUserBundle:
                namespace_prefix: FOS\UserBundle
                path: "%kernel.root_dir%/serializer/FOSUserBundle"



lexik_jwt_authentication:
    # APACHE webserver needs this to add in /etc/apache2/apache2.conf (or included extra file in sub folder sites-available)
    # <VirtualHost *:80>
    #	RewriteEngine on
    #	DocumentRoot /var/www/html
    #	RewriteCond %{HTTP:Authorization} ^(.*)
    #   RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
    # </VirtualHost>

    private_key_path: %kernel.root_dir%/var/jwt/private.pem   # ssh private key path
    public_key_path:  %kernel.root_dir%/var/jwt/public.pem    # ssh public key path
    pass_phrase:      "%jwt_ssh_key_passphrase%"                      # ssh key pass phrase included from parameters.yml
    token_ttl:        86400                                   # token ttl - defaults to 86400



# liip_functional_test added in config_test.yml