# liip_functional_test added in .config_test.yml

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~                                      # handler_id set to null will use default session handler from php.ini
    fragments:       ~
    http_method_override: true
    translator: { fallbacks: en }                           # language(-file) if requested translation file is not found
    default_locale:  de                                     # for links, when no favorite given default %locale%

services:
    fos_user.doctrine_registry:
        alias: doctrine                                     # github.com/FriendsOfSymfony/FOSUserBundle/issues/2048

sensio_framework_extra:
    view: { annotations: false }                            # FOSRestBundle takes over the controller annotations handling for views


twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"


doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

swiftmailer:                                                # email server configuration for 'mailer' service
    transport:  "%mailer_transport%"
    encryption: "%mailer_encryption%"
    auth_mode:  "%mailer_auth_mode%"
    port:       "%mailer_port%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:     { type: memory }                             # sends after request is completely processed (w/o exception or error)


fos_rest:
    param_fetcher_listener: true                            # Enable request's query-body like ?foo=bar
    format_listener: true                                   # Allow to request a format like api/foo/2.json
    body_listener:                                          # Allow different request formats like app/json
        decoders:
          json: fos_rest.decoder.jsontoform
          xml: fos_rest.decoder.xml

    view:
        view_response_listener: 'force'                     # Enable & force to return a view instance like @View()
        formats:
            xml: true
            json : true
        templating_formats:                                 # template for rendering via templating service
            html: false                                     # false to don't have to support separate twig templates
        force_redirects:
            html: true                                      # default
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json                                # if none is set via URL


fos_user:
    db_driver:      orm
    firewall_name:  admino
    user_class:     Barra\RecipeBundle\Entity\User


jms_serializer:                                             # JMS exlusion for 3th party entites needs to be done via config file
    metadata:
        directories:
            FOSUserBundle:
                namespace_prefix: FOS\UserBundle
                path: "%kernel.root_dir%/serializer/FOSUserBundle"



lexik_jwt_authentication:
    # <VirtualHost *:80>
    #	RewriteEngine on
    #	DocumentRoot /var/www/html
    #	RewriteCond %{HTTP:Authorization} ^(.*)
    #   RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
    # </VirtualHost>

    # overridden in config_test.yml to use committed test ssh keys
    private_key_path: %kernel.root_dir%/var/jwt/private.pem   # ssh private key path
    public_key_path:  %kernel.root_dir%/var/jwt/public.pem    # ssh public key path
    pass_phrase:      "%jwt_prod_ssh_key_pp%"                 # ssh key pass phrase included from parameters.yml
    token_ttl:        86400                                   # token ttl - defaults to 86400
