imports:
    - { resource: config_dev.yml }

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true



framework:
    test: ~
    profiler:
        collect: false
    session:
        storage_id: session.storage.mock_file                       # LiipFunctionalTest (default .filesystem')
        name: api