imports:
    - { resource: config_dev.yml }

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true



framework:
    test: ~
    session:
        storage_id: session.storage.filesystem  # instead of mock_file
        name: WSSE                              # both for liipBundle
    profiler:
        collect: false

liip_functional_test:
    authentication: # same for user fixture
        username: rest
        password: xVimiBXn6KFmqv1nFHiwGUY0lfGjvcg29KtzT1u8qmnWErSDyuANGSNEU7RIAMYucDfBAJSld4UaoZ3IPLsYIw==