imports:
    - { resource: config_dev.yml }

doctrine: # create SQLite DB before every test
    dbal:
        connections:
            default:
                driver: pdo_sqlite
                path: "%kernel.cache_dir%/test.db"
        default_connection: default

framework:
    profiler: # required for liip_functional_test.query.max_query_count
        collect: true
        enabled: true
    session:
        storage_id: session.storage.mock_file
    test: ~

liip_functional_test:
    cache_sqlite_db: true # creates backups/caches of every SQLite DB with fixtures
    query:
        max_query_count: 50 # max DB queries per test

swiftmailer:
    disable_delivery: true

web_profiler:
    intercept_redirects: false
    toolbar: false
