imports:
    - { resource: config_dev.yml }

doctrine: # create SQLite DB before every test
    dbal:
        connections:
            default:
                driver: pdo_sqlite
                path: "%kernel.cache_dir%/test.db"
        default_connection: default

framework:
    profiler: # required for liip_functional_test.query.max_query_count
        collect: true
        enabled: true
    session:
        storage_id: session.storage.mock_file
    test: ~

lexik_jwt_authentication: # separate, commited SSH keys for func. tests
    pass_phrase: "%jwt_test_ssh_key_pp%" # this passphrase is commited as well
    private_key_path: "%kernel.root_dir%/var/jwt/private-test.pem"
    public_key_path: "%kernel.root_dir%/var/jwt/public-test.pem"

liip_functional_test:
    cache_sqlite_db: true # creates backups/caches of every SQLite DB with fixtures
    query:
        max_query_count: 50 # max DB queries per test

swiftmailer:
    disable_delivery: true

web_profiler:
    intercept_redirects: false
    toolbar: false
