imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

doctrine:
    dbal:
        charset: UTF8
        dbname: "%database_name%"
        driver: pdo_mysql
        host: "%database_host%"
        password: "%database_password%"
        port: "%database_port%"
        user: "%database_user%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore

fos_rest:
    access_denied_listener:
        json: true
    allowed_methods_listener: true
    body_listener: # normalises requests' body
        array_normalizer: fos_rest.normalizer.camel_keys # serialize model properties in camelCase
        default_format: 'json'
        decoders:
          json: fos_rest.decoder.json
    exception: true # Activates the FOSRestBundle exception controller
    param_fetcher_listener: force # set configured parameter as request parameter
    routing_loader:
        default_format: json
    unauthorized_challenge: 'Basic realm="Restricted Area"' # sent as challenge header
    view:
        default_engine: twig
        failed_validation: 'HTTP_BAD_REQUEST'
        force_redirects: # redirect via View::createRouteRedirect()
            json: true
        formats: # formats rendered via JMS serializer
            json : true
        templating_formats: # formats requiring a template for rendering (twig)
            html: true
        view_response_listener: 'force' # api controller return View obj, which need to be resolved to Response obj

fos_user:
    db_driver: orm
    firewall_name: admino
    user_class: AppBundle\Entity\User

framework:
    assets:
        json_manifest_path: '%kernel.root_dir%/../web/manifest.json'
    csrf_protection: ~
    default_locale: '%locale%'
#    esi: ~
    form: ~
    fragments: ~
    http_method_override: true
#    php_errors:
#        log: true
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    secret: "%secret%"
#    serializer: { enable_annotations: true }
    session:
        handler_id: ~
#       deactivated for vagrant
#       handler_id: session.handler.native_file
#       save_path: "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    templating:
        engines: ['twig']
    translator: { fallbacks: ["%locale%"] }
    trusted_hosts: ~
    trusted_proxies: ~
    validation: { enable_annotations: true }

jms_serializer: # JMS exlusion for 3th party entites needs to be done via config file
    metadata:
        directories:
            FOSUserBundle:
                namespace_prefix: FOS\UserBundle
                path: "%kernel.root_dir%/serializer/FOSUserBundle"

parameters:
    locale: en

services:
    fos_user.doctrine_registry:
        alias: doctrine # github.com/FriendsOfSymfony/FOSUserBundle/issues/2048

sensio_framework_extra:
    view:
      annotations: true # FOSRestBundle takes over the controller annotations handling for views

swiftmailer:
    auth_mode: "%mailer_auth_mode%"
    delivery_address: "%mailer_user%"
    encryption: "%mailer_encryption%"
    host: "%mailer_host%"
    password: "%mailer_password%"
    port: "%mailer_port%"
    spool: { type: memory } # sends after request is completely processed (w/o exception or error)
    transport: "%mailer_transport%"
    username: "%mailer_user%"

twig:
    form_themes: ['bootstrap_3_layout.html.twig'] # or bootstrap_3_horizontal_layout.html.twig
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
