root:
    path: /
    defaults:
      _controller: FrameworkBundle:Redirect:navigate
      route: app_root_i18n
      permanent: true
    options:
        expose: true

api:
    type: rest
    resource: "@AppBundle/Resources/config/routing_api.yml"
    prefix: /{_locale}/api
    options:
        expose: true

app:
    resource: "@AppBundle/Controller"
    type: annotation
    prefix: /{_locale}
    options:
        expose: true

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /{_locale}
    options:
        expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
