redirect_root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: app_root_i18n
        permanent: true

api:
    type: rest
    resource: "@AppBundle/Resources/config/routing_api.yml"
    prefix: /{_locale}/api
    requirements:
        _locale: "[a-z]{2}"
    options:
        expose: true

app:
    resource: "@AppBundle/Controller"
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: "[a-z]{2}"
    options:
        expose: true

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /{_locale}
    requirements:
        _locale: "[a-z]{2}"
    options:
        expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
