barra_front_redirect:
    path: /
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: barra_front_root
      permanent: true
    options:
        expose: true

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}/admino
    options:
        expose: true

barra_rest:
    type:     rest
    resource: "@BarraRestBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/api
    options:
        expose: true

barra_front:
    resource: "@BarraFrontBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    options:
        expose: true

barra_admin:
    resource: "@BarraAdminBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admino
    options:
        expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
