barra_front_redirect:
    path: /
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: barra_front_root
      permanent: true


barra_rest:
    type:     rest
    resource: "@BarraRestBundle/Resources/config/routing.yml"
    prefix:   /api

barra_front:
    resource: "@BarraFrontBundle/Resources/config/routing.yml"
    prefix:   /{_locale}

barra_back:
    resource: "@BarraBackBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admino

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}/admino

