security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        admino:
            anonymous: ~ #would enable setting IS_AUTHENTICATED_ANONYMOUSLY in security.access_control
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: app_dashboard
                provider: fos_userbundle
                require_previous_session: false #no session required for auth. request (funcTests)
#                success_handler: lexik_jwt_authentication.handler.authentication_success # returns JWT
#                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            logout:
                path: fos_user_security_logout
                target: app_contact
            pattern: ^/[a-z][a-z]/admino
            remember_me:
                always_remember_me: true #set always cookie, alternatively to optional checkbox
                name: vpitAuth
                path: /
                secret: "%secret%"

        api:
            pattern: ^/[a-z][a-z]/api(?!/inquiries)
            provider: fos_userbundle
            stateless: true
            lexik_jwt:
                authorization_header: #instead of query parameter
                    enabled: true
                    prefix: Bearer #format "Authorization: Bearer {receivedtToken}"
