security:
    firewalls:
        secured_area:
            pattern:   ^/[a-z][a-z]/admino/
            anonymous: ~
            form_login:
                login_path:           barra_security_login
                check_path:           barra_security_login_check
                default_target_path:  barra_back_admin
                csrf_provider:        form.csrf_provider
                intention:            loginToken
            logout:
                path:                 barra_security_logout
                target:               barra_front_contact
            http_basic:
                realm: "Secured Admino"

    #role_hierarchy:
        #ROLE_ADMIN: ROLE_REST # ROLE_ADMIN >= ROLE_REST http://localhost/barra/vpit/web/app_dev.php/api/recipes/18

    access_control:
        - { path: ^/api/, roles: ROLE_REST }
        - { path: ^/[a-z][a-z]/admino/login, roles: IS_AUTHENTICATED_ANONYMOUSLY } #requires_channel: https }
        - { path: ^/[a-z][a-z]/admino/, roles: ROLE_ADMIN }

    providers:
        in_memory:
            memory:
                users:
                    rest:
                        password: $2a$10$NMWOFecCv5NmLvM9hBT53.CEXsto.mJ/FFrzMOkTaGxClmBUqxowG
                        roles: 'ROLE_REST' # used for disable_csrf_role in config.yml
                    barra:
                        password: $2a$12$c2wRxCd4fCzLt3gWhnKuh.BLFYl/sgqjpHrxRB32.gVXtdDnr7GVi
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12