security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        admino:
            pattern:                  ^/[a-z][a-z]/admino/.*
            anonymous:                true                                                      # to enable IS_AUTHENTICATED_ANONYMOUSLY
            form_login:                                                                         # redirects unauth. requests to this form
                provider:             fos_userbundle                                            # declared at the top
                csrf_provider:        form.csrf_provider
                login_path:           fos_user_security_login                                   # controller which handles login form's data
                check_path:           fos_user_security_check                                   # Login Form target (action)
                default_target_path:  barra_back_user                                           # if redirected from /login
                                                                                                # succes_handler for api firewall (breaks redirect though)
                success_handler:      lexik_jwt_authentication.handler.authentication_success   # returns the JWT token JSON after successful login
                failure_handler:      lexik_jwt_authentication.handler.authentication_failure   # returns bad login JSON object
            logout:
                path:                 fos_user_security_logout                                  # initialize logout process
                target:               barra_front_root                                          # redirect target after logged out

        api:
            pattern:                  ^/api/.*
            stateless:                true
            anonymous:                true
            provider:                 fos_userbundle                                            # declared at the top
            methods:                  [POST, PUT, DELETE]                                       # GET keeps free for public pages
            lexik_jwt:
                authorization_header:
                    enabled:          true
                    prefix:           Bearer



    role_hierarchy: #Admin >= User
        ROLE_ADMIN:                               ROLE_USER
        ROLE_SUPER_ADMIN:                         ROLE_ADMIN


    access_control:
        - { path: ^/api/,                         role: ROLE_ADMIN } #, requires_channel: https
        - { path: ^/[a-z][a-z]/admino/login$,     role: IS_AUTHENTICATED_ANONYMOUSLY }          # excluding login_check
      # - { path: ^/[a-z][a-z]/admino/register,   role: IS_AUTHENTICATED_ANONYMOUSLY }          # todo overwrite form & include user view
      # - { path: ^/[a-z][a-z]/admino/resetting,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z][a-z]/admino,            role: ROLE_ADMIN } #, requires_channel: https