security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    firewalls:
        admino:
            pattern:                      ^/[a-z][a-z]/admino/.*
            anonymous:                    true                      # to allow anonymous in access_control below
            form_login:
                require_previous_session: false                     # no session required for auth. request (funcTests)
                provider:                 fos_userbundle
                csrf_provider:            form.csrf_provider        # enable CSRF protection in general
                login_path:               fos_user_security_login   # render login view and form
                check_path:               fos_user_security_check   # checks credentials
                default_target_path:      barra_back_user           # default redirect when user just targeted /login
                success_handler:          lexik_jwt_authentication.handler.authentication_success   # returns JWT
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
            logout:
                path:                     fos_user_security_logout
                target:                   barra_front_root
        api:
            pattern:                      ^/[a-z][a-z]/api/.*
            provider:                     fos_userbundle
            stateless:                    true                      # anonymous key not enabled
            methods:                      [POST, PUT, DELETE]       # GET keeps public
            lexik_jwt:
                authorization_header:
                    enabled:              true
                    prefix:               Bearer


    role_hierarchy: #Admin >= User
        ROLE_ADMIN:                       ROLE_USER
        ROLE_SUPER_ADMIN:                 ROLE_ADMIN


    access_control:
        - { path: ^/[a-z][a-z]/api/,              role: ROLE_ADMIN }
        - { path: ^/[a-z][a-z]/admino/login$,     role: IS_AUTHENTICATED_ANONYMOUSLY }
      # - { path: ^/[a-z][a-z]/admino/register,   role: IS_AUTHENTICATED_ANONYMOUSLY }
      # - { path: ^/[a-z][a-z]/admino/resetting,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z][a-z]/admino,            role: ROLE_ADMIN }