security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        admino:
            pattern:   ^/[a-z][a-z]/admino                         # REST (/api) will be secured via WSSE authentication
            anonymous: ~
            #http_basic: ~

            form_login:                                             # redirect user requests for authentication (for FW admino) to this form
                provider:             fos_userbundle                # declared at the top
                csrf_provider:        form.csrf_provider

                login_path:           fos_user_security_login       # controller which handles login form's data
                check_path:           fos_user_security_check       # Login Form target after authentication for authorization
                default_target_path:  barra_back_user               # if /login was user's target so no aim is known

            logout:
                path:                 fos_user_security_logout      # initialize logout process
                target:               barra_front_root              # redirect target after logged out

    role_hierarchy: #Admin >= User
        ROLE_ADMIN:                   [ROLE_REST, ROLE_USER]        # REST != USER, 'cause CSRF isn't activated for REST users
        ROLE_SUPER_ADMIN:             ROLE_ADMIN

    access_control:
        - { path: ^/api/, roles: ROLE_REST }
        - { path: ^/[a-z][a-z]/admino/login$,     role: IS_AUTHENTICATED_ANONYMOUSLY } # excluding login_check
      # - { path: ^/[a-z][a-z]/admino/register,   role: IS_AUTHENTICATED_ANONYMOUSLY } # todo overwrite form & include user view
      # - { path: ^/[a-z][a-z]/admino/resetting,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z][a-z]/admino,            role: ROLE_ADMIN }

