security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        app:
            anonymous: true
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login # url for rendering login template & setting PHP_SESSION cookie
                check_path: fos_user_security_check # endpoint for POST with credentials (checks for PHP_SESSION as well)
            logout:
                path: fos_user_security_logout
                target: app_root_i18n
            pattern: ^/
            remember_me:
                always_remember_me: true
                name: appAuth
                path: /
                secret: "%secret%"
#            stateless: true
