security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        app:
            anonymous: true
            form_login:
                provider: fos_userbundle
                # starts PHP_SESSION
                # renders template with login form
                login_path: fos_user_security_login

                # sets remember_me cookie
                # see AppBundle\Service\Authentication*Handler for overridden response
                require_previous_session: false
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: app_root_i18n
            pattern: ^/
            remember_me:
                always_remember_me: true
                name: appAuth
                path: /
                secret: "%secret%"
            stateless: true
