security:
    firewalls:
        secured_area:
            pattern:   ^/admino/
            anonymous: ~
            form_login:
                login_path: barra_login
                check_path: barra_login_check
             #   default_target_path: barra_back
            logout:
                path:   barra_logout
                target: admino/
            http_basic:
                realm: "Secured Demo Area"

#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false

#        login:
#            pattern:  ^/demo/secured/login$
#            security: false


#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/admino/login, roles: IS_AUTHENTICATED_ANONYMOUSLY } #requires_channel: https }
        - { path: ^/admino/, roles: ROLE_ADMIN, }

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
