services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true # due to multiple service instances for same class --> custom service ids.

    app.request_decorator.recipe_composite_decorator:
        class: AppBundle\RequestDecorator\Factory\CompositeRequestDecoratorFactory
        calls:
          - [addFactory, ['@AppBundle\RequestDecorator\Factory\VeganRequestDecoratorFactory']]
          - [addFactory, ['@AppBundle\RequestDecorator\Factory\NameRequestDecoratorFactory']]
          - [addFactory, ['@AppBundle\RequestDecorator\Factory\SortNameRequestDecoratorFactory']]
          - [addFactory, ['@AppBundle\RequestDecorator\Factory\SortUpdatedRequestDecoratorFactory']]

    app.request_decorator.product_composite_decorator:
        class: AppBundle\RequestDecorator\Factory\CompositeRequestDecoratorFactory
        calls:
          - [addFactory, ['@AppBundle\RequestDecorator\Factory\VeganRequestDecoratorFactory']]
          - [addFactory, ['@AppBundle\RequestDecorator\Factory\NameRequestDecoratorFactory']]
          - [addFactory, ['@AppBundle\RequestDecorator\Factory\SortNameRequestDecoratorFactory']]
          - [addFactory, ['@AppBundle\RequestDecorator\Factory\SortUpdatedRequestDecoratorFactory']]
