imports:
    - { resource: services_request_decorator.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,DataFixtures,DependencyInjection,Form,Model}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments'] # allow actions(!) to get services injected

    AppBundle\EventListener\AccessDeniedListener:
        arguments:
            $formats: ''
            $challenge: ''
            $controller: ''

    security.authentication.success_handler:
        class:  AppBundle\Service\AuthenticationSuccessHandler
        arguments:  [ "@security.http_utils", {} ]
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    security.authentication.failure_handler:
        class:  AppBundle\Service\AuthenticationFailureHandler
        arguments:  [ "@http_kernel", "@security.http_utils", {}, "@logger" ]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
