imports:
    - { resource: services_request_decorator.yml }
    - { resource: services_repositories.yml }

services:
    app.service.inquiry:
        class: AppBundle\Service\InquiryService
        arguments: [ "@mailer" ]

    app.service.pagination_response_factory:
        class: AppBundle\Service\PaginationResponseFactory
