barra_front_root:
    path:     /
    defaults: { _controller: BarraFrontBundle:Contact:index }
    requirements:
      _locale: de|en

barra_front_contact:
    path:     /contact
    defaults: { _controller: BarraFrontBundle:Contact:index }

barra_front_recipes:
    path:     /recipes/{paginationActive}
    defaults: { _controller: BarraFrontBundle:Recipe:index, paginationActive: 1 }
    requirements:
      paginationActive: \d+

barra_front_recipe:
    path:     /recipe/{name}
    defaults: { _controller: BarraFrontBundle:Recipe:showRecipe }