barra_front_me_redirect:
    path: /
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: barra_front_me
      permanent: true

barra_front_me:
    path:     /{_locale}
    defaults: { _controller: BarraFrontBundle:Me:index }
    requirements:
      _locale: en|de




barra_front_references:
    path:     /{_locale}/references
    defaults: { _controller: BarraFrontBundle:Reference:index }

barra_front_reference:
    path:     /{_locale}/reference/{id}
    defaults: { _controller: BarraFrontBundle:Reference:showReference, id: 1 }
    requirements:
      id: \d+




barra_front_recipes:
    path:     /{_locale}/recipes
    defaults: { _controller: BarraFrontBundle:Recipe:index }

barra_front_recipe:
    path:     /{_locale}/recipe/{id}
    defaults: { _controller: BarraFrontBundle:Recipe:showRecipe, id: 1 }
    requirements:
      id: \d+




barra_front_contact:
    path:     /{_locale}/contact
    defaults: { _controller: BarraFrontBundle:Contact:index }

