barra_front_me:
    path:     /
    defaults: { _controller: BarraFrontBundle:Me:index }
    requirements:
      _locale: en|de




barra_front_references:
    path:     /references
    defaults: { _controller: BarraFrontBundle:Reference:index }

barra_front_reference:
    path:     /reference/{id}
    defaults: { _controller: BarraFrontBundle:Reference:showReference, id: 1 }
    requirements:
      id: \d+




barra_front_recipes:
    path:     /recipes
    defaults: { _controller: BarraFrontBundle:Recipe:index }

barra_front_recipe:
    path:     /recipe/{id}
    defaults: { _controller: BarraFrontBundle:Recipe:showRecipe, id: 1 }
    requirements:
      id: \d+




barra_front_contact:
    path:     /contact
    defaults: { _controller: BarraFrontBundle:Contact:index }

