barra_front_me:
    path:     /
    defaults: { _controller: BarraFrontBundle:Me:index }
    requirements:
      _locale: en|de




barra_front_references:
    path:     /references
    defaults: { _controller: BarraFrontBundle:Reference:index }




barra_front_recipes:
    path:     /recipes/{paginationActive}
    defaults: { _controller: BarraFrontBundle:Recipe:index, paginationActive: 1 }
    requirements:
        paginationActive: \d+

barra_front_recipe:
    path:     /recipe/{name}
    defaults: { _controller: BarraFrontBundle:RecipeDetail:index }




barra_front_contact:
    path:     /contact
    defaults: { _controller: BarraFrontBundle:Contact:index }

