barra_back_user:
  path:     /
  defaults: { _controller: BarraBackBundle:User:index }

barra_back_agencies:
  path:     /agencies/{pageIndex}
  defaults: { _controller: BarraBackBundle:Agency:index, pageIndex: 1 }
  requirements:
    pageIndex: \d+

barra_back_manufacturers:
  path:     /manufacturers/{pageIndex}
  defaults: { _controller: BarraBackBundle:Manufacturer:index, pageIndex: 1 }
  requirements:
    pageIndex: \d+

barra_back_measurements:
  path:     /measurements/{pageIndex}
  defaults: { _controller: BarraBackBundle:Measurement:index, pageIndex: 1 }
  requirements:
    pageIndex: \d+

barra_back_products:
  path:     /products/{pageIndex}
  defaults: { _controller: BarraBackBundle:Product:index, pageIndex: 1 }
  requirements:
    pageIndex: \d+

barra_back_recipes:
  path:     /recipes/{pageIndex}
  defaults: { _controller: BarraBackBundle:Recipe:index, pageIndex: 1 }
  requirements:
    pageIndex: \d+

barra_back_recipe:
  path:     /recipe/{name}
  defaults: { _controller: BarraBackBundle:Recipe:showRecipe }

barra_back_references:
    path:     /references/{pageIndex}
    defaults: { _controller: BarraBackBundle:Reference:index, pageIndex: 1 }
    requirements:
        pageIndex: \d+

barra_back_screenshot:
    path:     /screenshots/{id}
    defaults: { _controller: BarraBackBundle:Screenshot:index }
    requirements:
        id: \d+

barra_back_techniques:
  path:     /techniques/{pageIndex}
  defaults: { _controller: BarraBackBundle:Technique:index, pageIndex: 1 }
  requirements:
    pageIndex: \d+