barra_back_admin:
    path:     /
    defaults: { _controller: BarraBackBundle:Admin:index }
    requirements:
      _locale: en|de





barra_back_references:
    path:     /references
    defaults: { _controller: BarraBackBundle:Reference:index}

barra_back_reference_delete:
    path:     /reference/delete/{website}
    defaults: { _controller: BarraBackBundle:Reference:deleteReference }





barra_back_recipes:
    path:     /recipes
    defaults: { _controller: BarraBackBundle:Recipe:index }

barra_back_recipe_update:
    path:     /recipes/update/ajax
    defaults: { _controller: BarraBackBundle:Recipe:update }
    requirements:
        _method: POST

barra_back_recipe_delete:
    path:     /recipe/delete/{id}
    defaults: { _controller: BarraBackBundle:Recipe:delete }
    requirements:
        id: \d+





barra_back_recipeDetail:
    path:     /recipe/{name}
    defaults: { _controller: BarraBackBundle:RecipeDetail:index }



barra_back_recipeDetail_ingredient_update:
    path:     /recipe/ingredient/update/ajax
    defaults: { _controller: BarraBackBundle:RecipeDetail:updateIngredient }
    requirements:
        _method: POST

barra_back_recipeDetail_ingredient_delete:
    path:     /recipe/ingredient/delete/{recipeId}/{ingredientId}
    defaults: { _controller: BarraBackBundle:RecipeDetail:deleteIngredient }
    requirements:
        recipeId: \d+
        ingredientId: \d+



barra_back_recipeDetail_cookingStep_update:
    path:     /recipe/cookingstep/update/ajax
    defaults: { _controller: BarraBackBundle:RecipeDetail:updateCookingStep }
    requirements:
        _method: POST

barra_back_recipeDetail_cookingStep_swap:
    path:     /recipe/cookingstep/swap/{recipeId}/{posBefore}/{posAfter}/ajax
    defaults: { _controller: BarraBackBundle:RecipeDetail:swapCookingStep }
    requirements:
        recipeId: \d+
        posBefore: \d+
        posAfter: \d+

barra_back_recipeDetail_cookingStep_delete:
    path:     /recipe/cookingstep/delete/{recipeId}/{position}
    defaults: { _controller: BarraBackBundle:RecipeDetail:deleteCookingStep }
    requirements:
        recipeId: \d+
        position: \d+



barra_back_recipeDetail_file_upload:
    path:     /recipe/file/upload/ajax
    defaults: { _controller: BarraBackBundle:RecipeDetail:uploadFile }
    requirements:
        _method: POST

barra_back_recipeDetail_file_get:
    path:     /recipe/file/get/{recipeId}/ajax
    defaults: { _controller: BarraBackBundle:RecipeDetail:getFiles }
    requirements:
        recipeId: \d+

barra_back_recipeDetail_file_delete:
    path:     /recipe/file/delete/{recipeId}/{id}
    defaults: { _controller: BarraBackBundle:RecipeDetail:deleteFile }
    requirements:
        recipeId: \d+
        id: \d+





barra_back_ingredients:
    path:     /ingredients
    defaults: { _controller: BarraBackBundle:Ingredient:index }

barra_back_ingredient_update:
    path:     /ingredients/update/ajax
    defaults: { _controller: BarraBackBundle:Ingredient:update }
    requirements:
        _method: POST

barra_back_ingredient_delete:
    path:     /ingredients/delete/{id}
    defaults: { _controller: BarraBackBundle:Ingredient:delete }
    requirements:
        id: \d+





barra_back_manufacturers:
    path:     /manufacturers
    defaults: { _controller: BarraBackBundle:Manufacturer:index }

barra_back_manufacturer_update:
    path:     /manufacturers/update/ajax
    defaults: { _controller: BarraBackBundle:Manufacturer:update }
    requirements:
        _method: POST

barra_back_manufacturer_delete:
    path:     /manufacturers/delete/{id}
    defaults: { _controller: BarraBackBundle:Manufacturer:delete }
    requirements:
        id: \d+





barra_back_measurements:
    path:     /measurements
    defaults: { _controller: BarraBackBundle:Measurement:index }

barra_back_measurement_update:
    path:     /measurements/update/ajax
    defaults: { _controller: BarraBackBundle:Measurement:update }
    requirements:
        _method: POST

barra_back_measurement_delete:
    path:     /measurements/delete/{id}
    defaults: { _controller: BarraBackBundle:Measurement:delete }
    requirements:
        id: \d+