barra_back_user:
    path:     /
    defaults: { _controller: BarraBackBundle:User:index }

barra_back_link_references:
    resource: "@BarraBackBundle/Resources/config/routes/reference.yml"

barra_back_link_techniques:
    resource: "@BarraBackBundle/Resources/config/routes/technique.yml"

barra_back_link_agencies:
    resource: "@BarraBackBundle/Resources/config/routes/agency.yml"

barra_back_link_measurement:
    resource: "@BarraBackBundle/Resources/config/routes/measurement.yml"

barra_back_link_manufacturer:
    resource: "@BarraBackBundle/Resources/config/routes/manufacturer.yml"

barra_back_link_products:
    resource: "@BarraBackBundle/Resources/config/routes/product.yml"

barra_back_link_recipe:
    resource: "@BarraBackBundle/Resources/config/routes/recipe.yml"