barra_back_admin:
    path:     /
    defaults: { _controller: BarraBackBundle:Admin:index }
    requirements:
      _locale: en|de




barra_back_references:
    path:     /references
    defaults: { _controller: BarraBackBundle:Reference:index}

barra_back_reference_delete:
    path:     /reference/delete/{website}
    defaults: { _controller: BarraBackBundle:Reference:deleteReference }





barra_back_recipes:
    path:     /recipes
    defaults: { _controller: BarraBackBundle:Recipe:index }

barra_back_recipe:
    path:     /recipe/{name}
    defaults: { _controller: BarraBackBundle:RecipeDetail:index }

barra_back_recipe_delete:
    path:     /recipe/delete/{id}
    defaults: { _controller: BarraBackBundle:Recipe:deleteRecipe }
    requirements:
        id: \d+




barra_back_recipeDetail_ingredient_delete:
    path:     /recipe/ingredient/delete/{recipeId}/{ingredientId}
    defaults: { _controller: BarraBackBundle:RecipeDetail:deleteIngredient }
    requirements:
        recipeId: \d+
        ingredientId: \d+

barra_back_recipeDetail_cookingStep_delete:
    path:     /recipe/cookingStep/delete/{recipeId}/{step}
    defaults: { _controller: BarraBackBundle:RecipeDetail:deleteCookingStep }
    requirements:
        recipeId: \d+
        step: \d+




barra_back_ingredients:
    path:     /ingredients
    defaults: { _controller: BarraBackBundle:Ingredient:index }

barra_back_ingredient_delete:
    path:     /ingredients/delete/{id}
    defaults: { _controller: BarraBackBundle:Ingredient:deleteIngredient }
    requirements:
        id: \d+




barra_back_manufacturers:
    path:     /manufacturers
    defaults: { _controller: BarraBackBundle:Manufacturer:index }

barra_back_manufacturer_update:
    path:     /manufacturers/update
    defaults: { _controller: BarraBackBundle:Manufacturer:update }

barra_back_manufacturer_delete:
    path:     /manufacturers/delete/{id}
    defaults: { _controller: BarraBackBundle:Manufacturer:delete }
    requirements:
        id: \d+



barra_back_measurements:
    path:     /measurements
    defaults: { _controller: BarraBackBundle:Measurement:index }

barra_back_measurement_delete:
    path:     /measurements/delete/{id}
    defaults: { _controller: BarraBackBundle:Measurement:deleteMeasurement }
    requirements:
        id: \d+