parameters:
#    barra_back.example.class: Barra\BackBundle\Example

services:
#    barra_back.example:
#        class: %barra_back.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
