#parameters:
#    barra_back.mailer.class:             Barra\BackBundle\Mailer
#    barra_back.mailer.transport:         sendmail
#    barra_back.newsletter_manager.class  Barra\BackBundle\Neswletter\NewsletterManager
#
#services:
#    barra_back.mailer:
#        class:     %barra_back.mailer.class%
#        arguments: ["%barra_back.mailer.transport%"]
#
#     barra_back.newsletter_manager:
#       class:      %barra_back.newsletter_manager.class%"
#       arguments:  ["@barra_back.mailer"]