Barra\BackBundle\Entity\Manufacturer:
  properties:
    name:
      - NotBlank: ~
      - Type: string


Barra\BackBundle\Entity\Product:
  properties:
    name:
      - NotBlank: ~
      - Type: string
    vegan:
      - Type: bool
    gr:
      - NotBlank: ~
      - Type: integer
      - GreaterThanOrEqual:
          value: 0
    kcal:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0
    protein:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0
    carbs:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0
    sugar:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0
    fat:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0
    gfat:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0


Barra\BackBundle\Entity\Recipe:
  properties:
    name:
      - NotBlank: ~
      - Type: string

Manager\ManagerBundle\Entity\Photo:
  properties:
    file:
      - File:
          maxSize: 2M
          mimeTypes: image/*

Barra\BackBundle\Entity\Measurement:
  properties:
    name:
      - NotBlank:
      - Type: string
    gr:
      - NotBlank: ~
      - Type: integer
      - GreaterThanOrEqual:
          value: 0


Barra\BackBundle\Entity\Ingredient:
  properties:
    amount:
      - Type: { type: integer , groups: [ingredient] }
      - GreaterThanOrEqual: { value: 0, groups: [ingredient] }


Barra\BackBundle\Entity\Cooking:
  properties:
    description:
      - NotBlank: ~
      - Type: string


Barra\BackBundle\Entity\Reference:
  properties:
    url:
      - NotBlank:
      - Type: string
    description:
      - NotBlank:
      - Type: string
    started:
      - Date: ~
    finished:
      - Date: ~

Manager\ManagerBundle\Entity\Screenshot:
  properties:
    file:
      - File:
          maxSize: 2M
          mimeTypes: image/*

Barra\BackBundle\Entity\Agency:
  properties:
    name:
      - NotBlank:
      - Type: string
    url:
      - NotBlank:
      - Type: string


Barra\BackBundle\Entity\Technique:
  properties:
    name:
      - NotBlank:
      - Type: string
    description:
      - NotBlank:
      - Type: string
    url:
      - NotBlank:
      - Type: string
