Barra\FrontBundle\Entity\Manufacturer:
  properties:
    name:
      - NotBlank: ~
      - Type: string


Barra\FrontBundle\Entity\Product:
  properties:
    name:
      - NotBlank: ~
      - Type: string
    vegan:
      - Type: bool
    gr:
      - NotBlank: ~
      - Type: integer
      - GreaterThanOrEqual:
          value: 0
    kcal:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0
    protein:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0
    carbs:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0
    sugar:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0
    fat:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0
    gfat:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0


Barra\FrontBundle\Entity\Recipe:
  properties:
    name:
      - NotBlank: ~
      - Type: string

Manager\ManagerBundle\Entity\RecipePicture:
  properties:
    file:
      - File:
          maxSize: 2M
          mimeTypes: image/*

Barra\FrontBundle\Entity\Measurement:
  properties:
    type:
      - NotBlank:
      - Type: string
    gr:
      - NotBlank: ~
      - Type: integer
      - GreaterThanOrEqual:
          value: 0


Barra\FrontBundle\Entity\Ingredient:
  properties:
    amount:
      - Type: { type: integer , groups: [ingredient] }
      - GreaterThanOrEqual: { value: 0, groups: [ingredient] }


Barra\FrontBundle\Entity\Cooking:
  properties:
    description:
      - NotBlank: ~
      - Type: string


Barra\FrontBundle\Entity\Reference:
  properties:
    url:
      - NotBlank:
      - Type: string
    description:
      - NotBlank:
      - Type: string
    started:
      - Date: ~
    finished:
      - Date: ~

Manager\ManagerBundle\Entity\ReferencePicture:
  properties:
    file:
      - File:
          maxSize: 2M
          mimeTypes: image/*

Barra\FrontBundle\Entity\Agency:
  properties:
    name:
      - NotBlank:
      - Type: string
    url:
      - NotBlank:
      - Type: string


Barra\FrontBundle\Entity\Technique:
  properties:
    name:
      - NotBlank:
      - Type: string
    description:
      - NotBlank:
      - Type: string
    url:
      - NotBlank:
      - Type: string
