Barra\FrontBundle\Entity\Manufacturer:
  properties:
    name:
      - NotBlank: ~
      - Type: string
Barra\FrontBundle\Entity\Ingredient:
  properties:
    name:
      - NotBlank: ~
      - Type: string
    vegan:
      - NotBlank: ~
      - Type: bool
    kcal:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0
    protein:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0
    carbs:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0
    sugar:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0
    fat:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0
    gfat:
      - NotBlank: ~
      - Type: float
      - GreaterThanOrEqual:
          value: 0


Barra\FrontBundle\Entity\Recipe:
  properties:
    name:
      - NotBlank:
      - Type: string


Barra\FrontBundle\Entity\Measurement:
  properties:
    type:
      - NotBlank: { message: "back.measurement.type.notBlank" }
      - Type: string
    gr:
      - NotBlank: ~
      - Type: integer
      - GreaterThanOrEqual:
          value: 0

Barra\FrontBundle\Entity\RecipeIngredient:
  properties:
    amount:
      - NotBlank: { groups: [recipeIngredient] }
      - Type: { type: integer , groups: [recipeIngredient] }
      - GreaterThanOrEqual: { value: 0, groups: [recipeIngredient] }

Barra\FrontBundle\Entity\CookingStep:
  properties:
    description:
      - NotBlank: ~
      - Type: string
    step:
      - NotBlank: ~
      - Type: integer
      - GreaterThanOrEqual:
          value: 0