barra_back_user:
  path:     /
  defaults: { _controller: BarraAdminBundle:User:index }

barra_back_manufacturers:
  path:     /manufacturers/{pageIndex}
  defaults: { _controller: BarraAdminBundle:Manufacturer:index, pageIndex: 1 }
  requirements:
    pageIndex: \d+

barra_back_measurements:
  path:     /measurements/{pageIndex}
  defaults: { _controller: BarraAdminBundle:Measurement:index, pageIndex: 1 }
  requirements:
    pageIndex: \d+

barra_back_products:
  path:     /products/{pageIndex}
  defaults: { _controller: BarraAdminBundle:Product:index, pageIndex: 1 }
  requirements:
    pageIndex: \d+

barra_back_recipes:
  path:     /recipes/{pageIndex}
  defaults: { _controller: BarraAdminBundle:Recipe:index, pageIndex: 1 }
  requirements:
    pageIndex: \d+

barra_back_recipe:
  path:     /recipe/{name}
  defaults: { _controller: BarraAdminBundle:Recipe:showRecipe }