parameters:
    barra_back.formValidation.class:    Barra\AdminBundle\Service\FormValidation
    barra_back.formValidation.myParam: "unused Parameter"

services:
    barra_back.formValidation:
        class:     %barra_back.formValidation.class%
        arguments: ["%barra_back.formValidation.myParam%"]








#parameters:
#    barra_back.mailer.class:             Barra\AdminBundle\Mailer
#    barra_back.mailer.transport:         sendmail
#    barra_back.newsletter_manager.class  Barra\AdminBundle\Neswletter\NewsletterManager
#
#services:
#    barra_back.mailer:
#        class:     %barra_back.mailer.class%
#        arguments: ["%barra_back.mailer.transport%"]
#
#     barra_back.newsletter_manager:
#       class:      %barra_back.newsletter_manager.class%"
#       arguments:  ["@barra_back.mailer"]