barra_rest_recipes:
  type: rest
  resource: "BarraRestBundle:Recipe"
  name_prefix: barra_api_

barra_rest_photos:
  type: rest
  parent: barra_rest_recipes
  resource: "BarraRestBundle:Photo"
  name_prefix: barra_api_

barra_rest_ingredients:
  type: rest
  parent: barra_rest_recipes
  resource: "BarraRestBundle:Ingredient"
  name_prefix: barra_api_

barra_rest_cookings:
  type: rest
  parent: barra_rest_recipes
  resource: "BarraRestBundle:Cooking"
  name_prefix: barra_api_

barra_rest_products:
  type: rest
  resource: "BarraRestBundle:Product"
  name_prefix: barra_api_

barra_rest_measurements:
  type: rest
  resource: "BarraRestBundle:Measurement"
  name_prefix: barra_api_

barra_rest_manufacturers:
  type: rest
  resource: "BarraRestBundle:Manufacturer"
  name_prefix: barra_api_
