barra_recipe_root:
  path:     /
  defaults: { _controller: BarraRecipeBundle:Index:contact }
  requirements:
    _locale: de|en

barra_recipe_contact:
  path:     /contact
  defaults: { _controller: BarraRecipeBundle:Index:contact }

barra_recipe_dashboard:
  path:     /admino/
  defaults: { _controller: BarraRecipeBundle:Index:dashboard }

barra_recipe_public:
  resource: "@BarraRecipeBundle/Resources/config/routes/public.yml"

barra_recipe_admin:
  resource: "@BarraRecipeBundle/Resources/config/routes/admin.yml"
  prefix:   /admino


