parameters:
#    barra_security.example.class: Barra\SecurityBundle\Example

services:
#    barra_security.example:
#        class: %barra_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
