api_inquiry:
  type: rest
  resource: "@AppBundle/Controller/Api/InquiryController.php"
  name_prefix: api_


api_recipes:
  type: rest
  resource: "@AppBundle/Controller/Api/RecipeController.php"
  name_prefix: api_

api_ingredients:
  type: rest
  parent: api_recipes
  resource: "@AppBundle/Controller/Api/IngredientController.php"
  name_prefix: api_

api_instructions:
  type: rest
  parent: api_recipes
  resource: "@AppBundle/Controller/Api/InstructionController.php"
  name_prefix: api_


api_products:
  type: rest
  resource: "@AppBundle/Controller/Api/ProductController.php"
  name_prefix: api_

api_measurements:
  type: rest
  resource: "@AppBundle/Controller/Api/MeasurementController.php"
  name_prefix: api_
