barra_default_me:
    path:     /{lang}
    defaults: { _controller: BarraDefaultBundle:Me:show, lang: de }
    requirements:
      lang: de|en




barra_default_references:
    path:     /references/{lang}
    defaults: { _controller: BarraDefaultBundle:Reference:showReferences, lang: de }
    requirements:
      lang: de|en

barra_default_reference:
    path:     /references/{id}/{lang}
    defaults: { _controller: BarraDefaultBundle:Reference:showReference, id: 1, lang: de }
    requirements:
      id: \d+
      lang: de|en




barra_default_recipes:
    path:     /recipes
    defaults: { _controller: BarraDefaultBundle:Recipe:showRecipes }

barra_default_recipe:
    path:     /recipes/{id}
    defaults: { _controller: BarraDefaultBundle:Recipe:showRecipe, id: 1 }
    requirements:
      id: \d+

barra_Default_recipe_delete:
    path:     /recipes/d/{id}
    defaults: { _controller: BarraDefaultBundle:Recipe:deleteRecipes, id: 1 }



barra_default_contact:
    path:     /contact/{lang}
    defaults: { _controller: BarraDefaultBundle:Contact:get, lang: de }
    #methods: [ GET ]
    requirements:
      lang: de|en

barra_default_contact:
    path:     /contact/{lang}
    defaults: { _controller: BarraDefaultBundle:Contact:post, lang: de }
    #methods : [ POST ]
    requirements:
      lang: de|en




