barra_default_me:
    path:     /{lang}
    defaults: { _controller: BarraDefaultBundle:Me:index, lang: de }
    requirements:
      lang: de|en




barra_default_admin:
    path:     /admino
    defaults: { _controller: BarraDefaultBundle:Admin:index }




barra_default_references:
    path:     /references/{lang}
    defaults: { _controller: BarraDefaultBundle:Reference:index, lang: de }
    requirements:
      lang: de|en

barra_default_reference:
    path:     /references/{id}/{lang}
    defaults: { _controller: BarraDefaultBundle:Reference:showReference, id: 1, lang: de }
    requirements:
      id: \d+
      lang: de|en




barra_default_recipes:
    path:     /recipes
    defaults: { _controller: BarraDefaultBundle:Recipe:index }

barra_default_recipe:
    path:     /recipes/{id}
    defaults: { _controller: BarraDefaultBundle:Recipe:showRecipe, id: 1 }
    requirements:
      id: \d+




barra_default_contact:
    path:     /contact/{lang}
    defaults: { _controller: BarraDefaultBundle:Contact:get, lang: de }
    #methods: [ GET ]
    requirements:
      lang: de|en

barra_default_contact:
    path:     /contact/{lang}
    defaults: { _controller: BarraDefaultBundle:Contact:post, lang: de }
    #methods : [ POST ]
    requirements:
      lang: de|en




