barra_back_measurements:
    path:     /measurements/{paginationActive}
    defaults: { _controller: BarraBackBundle:Measurement:index, paginationActive: 1 }
    requirements:
        paginationActive: \d+

barra_back_measurement_update:
    path:     /measurements/update/ajax
    defaults: { _controller: BarraBackBundle:Measurement:update }
    requirements:
        _method: POST

barra_back_measurement_delete:
    path:     /measurements/delete/{id}
    defaults: { _controller: BarraBackBundle:Measurement:delete }
    requirements:
        id: \d+