barra_back_products:
    path:     /products/{paginationActive}
    defaults: { _controller: BarraBackBundle:Product:index, paginationActive: 1 }
    requirements:
          paginationActive: \d+

barra_back_product_update:
    path:     /products/update/ajax
    defaults: { _controller: BarraBackBundle:Product:update }
    requirements:
        _method: POST

barra_back_product_delete:
    path:     /products/delete/{id}
    defaults: { _controller: BarraBackBundle:Product:delete }
    requirements:
        id: \d+