barra_back_recipes:
    path:     /recipes/{paginationActive}
    defaults: { _controller: BarraBackBundle:Recipe:index, paginationActive: 1 }
    requirements:
        paginationActive: \d+

barra_back_recipe_update:
    path:     /recipes/update/ajax
    defaults: { _controller: BarraBackBundle:Recipe:update }
    requirements:
        _method: POST

barra_back_recipe_delete:
    path:     /recipe/delete/{id}
    defaults: { _controller: BarraBackBundle:Recipe:delete }
    requirements:
        id: \d+





barra_back_recipeDetail:
    path:     /recipe/{name}
    defaults: { _controller: BarraBackBundle:RecipeDetail:index }



barra_back_recipeDetail_product_update:
    path:     /recipe/product/update/ajax
    defaults: { _controller: BarraBackBundle:Ingredient:update }
    requirements:
        _method: POST

barra_back_recipeDetail_product_swap:
    path:     /recipe/product/swap/{recipeId}/{posBefore}/{posAfter}/ajax
    defaults: { _controller: BarraBackBundle:Ingredient:swap }
    requirements:
        recipeId: \d+
        posBefore: \d+
        posAfter: \d+

barra_back_recipeDetail_product_delete:
    path:     /recipe/product/delete/{recipeId}/{productId}
    defaults: { _controller: BarraBackBundle:Ingredient:delete }
    requirements:
        recipeId: \d+
        productId: \d+



barra_back_recipeDetail_cooking_update:
    path:     /recipe/cookingstep/update/ajax
    defaults: { _controller: BarraBackBundle:Cooking:update }
    requirements:
        _method: POST

barra_back_recipeDetail_cooking_swap:
    path:     /recipe/cookingstep/swap/{recipeId}/{posBefore}/{posAfter}/ajax
    defaults: { _controller: BarraBackBundle:Cooking:swap }
    requirements:
        recipeId: \d+
        posBefore: \d+
        posAfter: \d+

barra_back_recipeDetail_cooking_delete:
    path:     /recipe/cookingstep/delete/{recipeId}/{position}
    defaults: { _controller: BarraBackBundle:Cooking:delete }
    requirements:
        recipeId: \d+
        position: \d+



barra_back_recipeDetail_picture_upload:
    path:     /recipe/picture/upload/ajax
    defaults: { _controller: BarraBackBundle:RecipeDetail:uploadPicture }
    requirements:
        _method: POST

barra_back_recipeDetail_pictures_get:
    path:     /recipe/picture/get/{recipeId}/ajax
    defaults: { _controller: BarraBackBundle:RecipeDetail:getPictures }
    requirements:
        recipeId: \d+

barra_back_recipeDetail_picture_delete:
    path:     /recipe/picture/delete/{recipeId}/{id}
    defaults: { _controller: BarraBackBundle:RecipeDetail:deletePicture }
    requirements:
        recipeId: \d+
        id: \d+