barra_back_references:
    path:     /references/{paginationActive}
    defaults: { _controller: BarraBackBundle:Reference:index, paginationActive: 1 }
    requirements:
        paginationActive: \d+

barra_back_reference_update:
    path:     /reference/update/ajax
    defaults: { _controller: BarraBackBundle:Reference:update }
    requirements:
        _method: POST

barra_back_reference_delete:
    path:     /reference/delete/{id}
    defaults: { _controller: BarraBackBundle:Reference:deleteReference }
    requirements:
        id: \d+