barra_back_techniques:
    path:     /techniques/{paginationActive}
    defaults: { _controller: BarraBackBundle:Technique:index, paginationActive: 1 }
    requirements:
        paginationActive: \d+

barra_back_technique_update:
    path:     /technique/update/ajax
    defaults: { _controller: BarraBackBundle:Technique:update }
    requirements:
        _method: POST

barra_back_technique_delete:
    path:     /technique/delete/{id}
    defaults: { _controller: BarraBackBundle:Technique:deleteTechnique }
    requirements:
        id: \d+